Feature/search postcode endpoint
Scottish-Natural-Heritage/gulls-health-and-safety-api pull request #1
Opened 2021-09-29 15:13 UTC by JohnJAMoore

Add endpoint to search postcodes

git@github.com:Scottish-Natural-Heritage/gulls-health-and-safety-api.git

2021-09-30 14:49 UTC, MikeCoats requested changes
A little tidying and a couple of questions - not much! :D

2021-09-30 14:49 UTC, MikeCoats commented on src/controllers/postcode-lookup-controller.ts
> +    });
A few things...

- We should try to be consistent using template literal strings as opposed to concatenation - you did it on the auth header correctly, but the url line uses the old way of doing it.
- Can you put the url base in an environment variable too - I'm not sure how long `cagmap` will be live and it's still on the `snh.gov.uk` domain so it might move soon.
- I'm not a fan of string concatenation for url params when there's a better option available to us.
- Should we be passing unchecked user input directly to another service? _Postel's rule_ says we should be lenient in what we accept as input, but strict in the quality of our output. I reckon we should probably pull in the naturescot-utils library which has a `isaRealUkPostcode` method available for us to check out input against.
- Since we're in modern TS/JS, you can tidy up the api key line with the [nullish coalescing operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator) `??` now.

I believe this could be better written as

```ts
    if (!formatters.isaRealUkPostcode(postcode)) {
      throw new Error('some suitable message');
    }

    const cleanPostcode =  formatters.formatPostcodeForPrinting(postcode);

    const severResponse: AxiosResponse = await axios.get(config.gazetterBaseUrl, {
      params: {
        postcode: cleanPostcode,
      },
      headers: {
        Authorization: `Bearer ${config.postcodeApiKey ?? ''}`,
      },
    });
```

2021-09-30 14:49 UTC, MikeCoats commented on src/controllers/postcode-lookup-controller.ts
> +    return addressResults.results[0].address;
What happens here if there are 0 results? Will this give us a 'cannot read property address of undefined' error?

2021-09-30 14:49 UTC, MikeCoats commented on src/routes.ts
> +      const postcodeQuery: string = _request.query.q as string;
This shouldn't be `_request`, just `request`. The `_` prefix is there to tell linters that you know it's **unused** but it's needed as part of the function's signature.

2021-09-30 14:49 UTC, MikeCoats commented on src/routes.ts
> +        return h.response(new Error('No Postcode provided')).code(500);
Does this work? Normally you can't 'JSONify' errors, only console-log them:

![image](https://user-images.githubusercontent.com/37802088/135478251-28521f85-16fd-411c-bde9-b63d8731b65e.png)

2021-10-04 13:47 UTC, JohnJAMoore commented on src/controllers/postcode-lookup-controller.ts
> +    return addressResults.results[0].address;
If the API doesnt get any matches you get this response so this code would fail good spot

{
    "results": [
        "No records found."
    ],
    "metadata": {
        "querytime": 0.01819,
        "vintage": 87,
        "jobid": null,
        "count": 0,
        "maxResults": 1000,
        "status": "OK"
    }
}

2021-10-05 07:08 UTC, MikeCoats requested changes
Two spelling mistakes, that's all.

2021-10-05 09:18 UTC, MikeCoats approved these changes
# 💥 

LGTM!

2021-10-05 09:19 UTC, merged