Feature/cron expired no final return
Scottish-Natural-Heritage/gulls-health-and-safety-api pull request #119
Opened 2023-02-03 12:39 UTC by paulcoxsnh

Issues:
https://github.com/Scottish-Natural-Heritage/Licensing/issues/1492
https://github.com/Scottish-Natural-Heritage/Licensing/issues/1494
https://github.com/Scottish-Natural-Heritage/Licensing/issues/1491

Adds three cron jobs, one for sending reminders on expired licences with no returns, one for expired licences with no final returns and one for soon to expire licences.

2023-02-04 14:11 UTC, finchie requested changes
Hi Paul,

Sorry for gate-crashing on this PR!

I actually just wanted to learn how the various cron jobs were implemented so I quickly scanned through this PR. Then I spotted a possible bug with reminder emails being sent twice to holders instead of once each to holder & applicant.

Then I'm afraid pedantry got the better of me & I spotted some other potential improvements that could be made.

2023-02-04 14:11 UTC, finchie commented on src/controllers/scheduled.ts
> +      emailReplyToId: '4b49467e-2a35-4713-9d92-809c55bf1cdd',
There's loads of [magic strings](https://methodpoet.com/magic-strings/) here! It would be much clearer to declare these strings as constants.

2023-02-06 08:58 UTC, finchie requested changes
Looks good Paul, except there's a linting error on line 26 of `src/config/app.ts`

2023-02-06 09:00 UTC, paulcoxsnh commented
@finchie Yeah not quite finished yet :)

2023-02-07 11:35 UTC, finchie approved these changes
Looking great! 💯

2023-02-07 11:36 UTC, merged